apiVersion: v1
kind: ConfigMap

metadata:
  name: otel-collector-config
  namespace: monitoring

data:
  otel-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      otlp:
        endpoint: tempo.monitoring.svc.cluster.local:4317
        tls:
          insecure: true

      logging:
        verbosity: detailed

    service:
      pipelines:
        traces:
          receivers:
            - otlp

          processors:
            - batch

          exporters:
            - otlp
            - logging
