apiVersion: apps/v1
kind: Deployment

metadata:
  name: otel-collector
  namespace: monitoring

spec:
  replicas: 1

  selector:
    matchLabels:
      app: otel-collector

  template:
    metadata:
      labels:
        app: otel-collector

    spec:
      containers:

      - name: otel-collector

        image: otel/opentelemetry-collector:0.102.1

        args:
          - "--config=/etc/otel-config.yaml"

        ports:
          - containerPort: 4317
          - containerPort: 4318

        volumeMounts:
          - name: config
            mountPath: /etc/otel-config.yaml
            subPath: otel-config.yaml

      volumes:
        - name: config
          configMap:
            name: otel-collector-config
